### ISSUE TITLE
Make a number guessing game with python 

### ISSUE THREAD

**Issue by debojeetjha10** [pranav2012/Python-fest2020#27]
A secret number will be generated and the user will have multiple chance to guess the number with each submission the program will tell him if the number is bigger than the secret number of smaller if not the same.

**Comment by debojeetjha10** [comment]
Can u assign me this @pranav2012

**Comment by pranav2012** [comment]
Merged

**Comment by debojeetjha10** [comment]
Great!!
Thanks @pranav2012

**Comment by zyberg2091** [comment]
hii,can i contribute to this project?

**Comment by pranav2012** [comment]
yes @zyberg2091

**Comment by debojeetjha10** [comment]
> hii,can i contribute to this project?

it will be great if you can add a gui to that!!!
use pygame or tinker
@zyberg2091
